apiVersion: 1

datasources:
  - name: MySQL-EventDB
    type: mysql
    url: mysql:3306
    database: event_db
    user: appuser
    secureJsonData:
      password: apppass
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
    isDefault: true
    editable: true
